name: C/C++ CI

env:
  CI: true

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: g++ -I ./ *.cpp ./*.cpp
