name: C/C++ CI

env:
  CI: true

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: g++ -D _GLFW_WIN32;GLEW_STATIC; -I ./GlEngine/vendor/include/ -g $(find . -type f -iregex ".*\.cpp")
