name: C/C++ CI

env:
  CI: true

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # Only use windows for now

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: g++ -I ./GLEngine/vendor/include/ -g -D GLEW_STATIC $(find . -type f -iregex ".*\.cpp")
